### ISSUE TITLE
Broke After upgrade?

### ISSUE THREAD

**Issue by VarunBatraIT** [fbacker/docker-opensubtitles#3]
I am getting this error now:

```
opensubtitles    | WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
opensubtitles    | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
opensubtitles    | (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'log' of null
opensubtitles    |     at file:///app/index.js:99:19
opensubtitles    | (Use `node --trace-warnings ...` to show where the warning was created)
opensubtitles    | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
opensubtitles    | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by VarunBatraIT** [comment]
After override JS I found that, GID and UID was incorrect - It is fixed

**Comment by VarunBatraIT** [comment]
It looks like if I don't override user - only then opensubtitle works. Perhaps you have permission issue with node_modules

**Comment by fbacker** [comment]
I quite don't understand when and how to work with the user and overrides. Do you have an example setup that I can try? Just released a new update that you can try.

```
  opensubtitles:
    image: fredrickbacker/opensubtitles:latest
    container_name: opensubtitles
    volumes:
      - /media/Movies:/movies
      - /media/Series:/series
      - /home/myuser/opensubtitles/tmp:/tmp
      - /home/myuser/opensubtitles/config:/config
    restart: unless-stopped
    environment:
      - TZ=Europe/Stockholm
      - PGID=1000
      - PUID=1000
```
